# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ReNumber
                                 A QGIS plugin
 This plugin allows you to define an incremented number of your features based on custom criterias and ordering
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-12-30
        copyright            : (C) 2020 by Paul-André Duchesne / Natagora asbl
        email                : paul-andre.duchesne@natagora.be
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ReNumber class from file ReNumber.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .re_number import ReNumber
    return ReNumber(iface)
